<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN509713" failures="1" tests="3" name="Default test" time="21.433" errors="0" timestamp="2024-11-08T16:51:03 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="18.579"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="20.579"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="20.887">
    <failure type="java.lang.AssertionError" message="expected [No] but found [Beetroot]">
      <![CDATA[java.lang.AssertionError: expected [No] but found [Beetroot]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepDefinations.OfferPageStepDefination.validate_Product_name_in_offers_page(OfferPageStepDefination.java:45)
at âœ½.validate Product name in offers page.(file:///C:/Users/2320611/eclipse-workspace/Selenium%20Rahul/CucumberFirstSteps/src/test/java/features/searchProduct.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
